# Generated by Django 5.0.4 on 2024-04-08 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_title_menuitem_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='menu_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.menuitem'),
            preserve_default=False,
        ),
    ]
